build:
	javac -Xlint:unchecked -classpath lib/zookeeper-3.3.2.jar:lib/log4j-1.2.15.jar ZkConnector.java Client.java InstructionPacket.java Tracker.java worker.java fileServer.java fileServerThread.java Packet.java

clean:
	rm -f *.class
